### ISSUE TITLE
Error Value: ('664 - horizontal.jpg', <type 'unicode'>, 'filename')

### ISSUE THREAD

**Issue by chinabhz** [plonegovbr/portal.buildout#21]
Estou tentando levantar um ambiente de desenvolvimento do portal, segui as instruções do link https://identidade-digital-de-governo-plone.readthedocs.org/en/latest/desenvolvimento/ e tudo ocorre sem nenhuma mensagem de erro. Porém, quando vou adicionar o novo site plone dá o erro abaixo:

2015-05-21 17:45:31 INFO Brasil: /assuntos
2015-05-21 17:45:31 INFO Brasil: /assuntos/editoria-a
2015-05-21 17:45:32 INFO Brasil: /assuntos/editoria-a/segundo-nivel
2015-05-21 17:45:32 INFO Brasil: /assuntos/editoria-a/segundo-nivel/terceiro-nivel
2015-05-21 17:45:32 INFO Brasil: /assuntos/editoria-a/segundo-nivel/terceiro-nivel/pagina-de-texto-institucional-a
2015-05-21 17:45:33 INFO Brasil: /assuntos/editoria-a/segundo-nivel/terceiro-nivel/pagina-de-texto-institucional-b
2015-05-21 17:45:34 INFO Brasil: /assuntos/editoria-a/segundo-nivel/pagina-de-texto-institucional
2015-05-21 17:45:34 INFO Brasil: /assuntos/editoria-a/capa-interna
2015-05-21 17:45:34 INFO Brasil: /assuntos/editoria-a/ultimas-noticias-da-editoria-a
2015-05-21 17:45:34 INFO Brasil: /assuntos/editoria-a/ultimas-noticias-da-editoria-a/copy_of_titulo-da-noticia-entre-35-e-90-caracteres-com-espaco
2015-05-21 17:45:35 ERROR Zope.SiteErrorLog 1432241135.070.886006060478 http://xxx.xxx.xxx.xxx:8080/@@plone-addsite
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module brasil.gov.portal.browser.plone.admin, line 73, in __call__
  Module Products.CMFPlone.factory, line 105, in addPloneSite
  Module Products.GenericSetup.tool, line 350, in runAllImportStepsFromProfile
   - __traceback_info__: profile-brasil.gov.portal:initcontent
  Module Products.GenericSetup.tool, line 1100, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1015, in _doRunImportStep
   - __traceback_info__: base-content
  Module brasil.gov.portal.setuphandlers, line 213, in importContent
  Module brasil.gov.portal.setuphandlers, line 22, in setupPortalContent
  Module collective.transmogrifier.transmogrifier, line 63, in __call__
  Module collective.transmogrifier.sections.savepoint, line 16, in __iter__
  Module collective.transmogrifier.sections.logger, line 39, in __iter__
  Module plone.app.transmogrifier.reindexobject, line 30, in __iter__
  Module plone.app.transmogrifier.browserdefault, line 24, in __iter__
  Module brasil.gov.portal.transmogrifier.sections.refactor, line 86, in __iter__
  Module brasil.gov.portal.transmogrifier.sections.refactor, line 50, in __iter__
  Module collective.jsonmigrator.mimetype, line 40, in __iter__
  Module brasil.gov.portal.transmogrifier.sections.datafields, line 70, in __iter__
  Module brasil.gov.portal.transmogrifier.sections.datafields, line 48, in fixattrs
  Module plone.namedfile.file, line 423, in __init__
  Module plone.namedfile.file, line 374, in __init__
  Module zope.schema.fieldproperty, line 52, in __set__
  Module zope.schema._bootstrapfields, line 182, in validate
  Module zope.schema._bootstrapfields, line 309, in _validate
  Module zope.schema._bootstrapfields, line 209, in _validate
WrongType: ('664 - horizontal.jpg', <type 'unicode'>, 'filename')

Meu ambiente é: sistema operacional Linux CentoS 5.5, plone Plone-4.3.4-r1-UnifiedInstaller.tgz instalado sem nenhuma mensagem de erro.
O método usado foi: instalar o plone incluindo na seção eggs do build,conf o "brasil.gov.portal", mas ao iniciar o serviço Plone não aparece nada do portal na hora de criar o novo site, mas consigo criar o novo site plone normalmente. 
Então derrubei o serviço Plone e iniciei o processo de instalar o portal em ambinete de desenvolvimento conforme indicado no link https://identidade-digital-de-governo-plone.readthedocs.org/en/latest/desenvolvimento/ , desde a clonagem do repositório até as especificidades do lxml para o centos. Novamente ocorre tudo OK e consigo subir o serviço Plone e aparece o logo do brasil.gov na hora de criar o novo site plone, mas ao mandar criar o novo site aparece o erro acima.

Estou a disposição para mais detalhes.

**Comment by chinabhz** [comment]
Pessoal, hoje fiz uma nova instalação do zero do Plone em uma máquina Ubuntu de testes, acrescentei o  brasil.gov.portal no buidout.cfg e rodei o buildout, iniciei o plone e criei o site plone do portal brasil com sucesso. Portanto creio ser algum erro de ambiente provocado pelo CentOS e não um bug no portal brasil. Vou continuar minhas tentativas e manterei vocês informados, até para o registro da solução aplicada.

**Comment by whereiswr** [comment]
@chinabhz, olá! Como você acrescentou a referência ao pacote `brasil.gov.portal` no arquivo `buildout.cfg`? Você se importaria em colar um trecho do código, por favor?

Estou com o mesmo problema. Clonei o `portal.buildout` num computador com Ubuntu 14.04 LTS, usando a versão 2.7.0 do Python graças ao [`pyenv`](https://github.com/yyuu/pyenv). Os processos de [_buildout_](https://identidade-digital-de-governo-plone.readthedocs.org/en/latest/producao/#buildout) e de [inicialização e controle](https://identidade-digital-de-governo-plone.readthedocs.org/en/latest/producao/#inicializacao-e-controle) funcionam corretamente, pois sigo o manual. Porém, quando clico em `Criar Portal`, aparece exatamente o mesmo erro: `Error Type: WrongType`, `Error Value: ('664 - horizontal.jpg', <type 'unicode'>, 'filename')`. :disappointed:

**Comment by idgserpro** [comment]
@chinabhz @whereiswr vocês instalaram as dependências do sistema operacional como indicado aqui?

http://identidade-digital-de-governo-plone.readthedocs.org/en/latest/base/#pacotes-do-sistema

**Comment by whereiswr** [comment]
@idgserpro, faltaram os pacotes `libjpeg62`, `libjpeg62-dev` e `libreadline-gplv2-dev` no meu sistema, pois já estavam instalados outros mais recentes: `libjpeg8`, `libjpeg8-dev` e `libreadline6-dev`. Depois que instalei as versões definidas na [documentação](https://identidade-digital-de-governo-plone.readthedocs.org/en/latest/base/#pacotes-do-sistema), ainda não funcionou, daí usei o `pyenv` para instalar o Python 2.7.3 (que é entregue por padrão no Ubuntu 12.10), então a criação de um novo portal padrão deu certo! :smile:

**Comment by chinabhz** [comment]
No meu caso, estava instalando no Centos e por isso tava dando problema.
Mas consegui contornar instalando o Plone puro e depois fazendo a
instalação do portal por cima. Mas minha visão falta gerar uma documentação
pra instalação mais genérica, pois nem todos tem domínio do ambiente.

Em sexta-feira, 5 de fevereiro de 2016, Will Rosa <notifications@github.com>
escreveu:

> @idgserpro <https://github.com/idgserpro>, faltaram os pacotes libjpeg62,
> libjpeg62-dev e libreadline-gplv2-dev no meu sistema, pois já estavam
> instalados outros mais recentes: libjpeg8, libjpeg8-dev e libreadline6-dev.
> Depois que instalei as versões definidas na documentação
> <https://identidade-digital-de-governo-plone.readthedocs.org/en/latest/base/#pacotes-do-sistema>,
> ainda não funcionou, daí usei o pyenv para instalar o Python 2.7.3 (que é
> entregue por padrão no Ubuntu 12.10), então a criação de um novo portal
> padrão deu certo! [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plonegovbr/portal.buildout/issues/21#issuecomment-180607910>
> .
>


-- 

Enviado de um dispositivo móvel

**Comment by idgserpro** [comment]
> Mas minha visão falta gerar uma documentação
pra instalação mais genérica, pois nem todos tem domínio do ambiente.

@chinabhz @whereiswr o que acha que podemos melhorar nessa documentação? Vocês já tinham algum conhecimento de ambiente (Python, virtualenv, dependências de sistema)? Dessa forma podemos trabalhar para fechar esse relato.

**Comment by whereiswr** [comment]
@idgserpro, fiz outros testes: criei uma VM com o [Ubuntu Server 14.04 LTS](http://releases.ubuntu.com/14.04/) e outra com [Xubuntu 14.04 LTS](http://cdimage.ubuntu.com/xubuntu/releases/14.04/release/); ambas foram _clean installs_. Segui as instruções do [manual](https://identidade-digital-de-governo-plone.readthedocs.org/en/latest/), mas tive que compilar e instalar a dependência [`threadframe 0.2`](https://majid.info/blog/threadframe-multithreaded-stack-frame-extraction-for-python/) manualmente, então consegui criar um portal padrão sem problemas nas VMs! Ou seja, o manual de vocês está correto :wink:

```bash
# Instalação de dependências, clonagem do repositório, criação do virtualenv
wget -S --delete-after http://www.plone.org/
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install -y build-essential libssl-dev libxml2-dev libxslt1-dev libbz2-dev zlib1g-dev python-setuptools python-dev python-virtualenv libjpeg62-dev libreadline-gplv2-dev python-imaging wv poppler-utils git
git clone https://github.com/plonegovbr/portal.buildout.git portal.buildout
cd ~/portal.buildout
virtualenv py27
source py27/bin/activate

# Instalação manual do pacote threadframe
cd ~
wget https://majid.info/python/threadframe/threadframe-0.2.tar.gz
tar xvf threadframe-0.2.tar.gz
cd threadframe-0.2/
python setup.py build
python setup.py install
cd ~/portal.buildout/

# Processo de buildout
python bootstrap.py -c buildout.cfg
./bin/buildout -c buildout.cfg
./bin/supervisord
./bin/supervisorctl status
```
O que sugiro é criar uma nota no manual alertando que, se houver outros pacotes e projetos na máquina (no meu caso, já estavam instalados: [`landsat-util`](http://landsat-util.readthedocs.org/en/latest/), [`scikit-image`](http://scikit-image.org/), [SciPy](http://www.scipy.org/) etc.), pode ser necessário instalar o Python usando o [`pyenv`](https://github.com/yyuu/pyenv), daí fazer a instalação do `portal.buildout`.

**Comment by idgserpro** [comment]
@whereiswr então o erro ```Error Type: WrongType, Error Value: ('664 - horizontal.jpg', <type 'unicode'>, 'filename')``` foi por causa da versão do python. Você estava utilizando o Python 2.7.0 quando ele ocorreu? Aí quando você utilizou o Ubuntu 14.04 (que vem com o python 2.7.6) funcionou? É isso?

**Comment by whereiswr** [comment]
@idgserpro, acho que foi isso, sim.

**Comment by idgserpro** [comment]
@chinabhz qual a versão do python você estava utilizando quando teve o problema?

**Comment by chinabhz** [comment]
Caras, nem lembro. Vou recuperar e posto depois.


Em sexta-feira, 12 de fevereiro de 2016, idgserpro <notifications@github.com>
escreveu:

> @chinabhz <https://github.com/chinabhz> qual a versão do python você
> estava utilizando quando teve o problema?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plonegovbr/portal.buildout/issues/21#issuecomment-183276972>
> .
>


-- 

Enviado de um dispositivo móvel

**Comment by idgserpro** [comment]
Não consegui rodar o buildout com o python 2.7.0 no ubuntun 12. Parece que tem um problema de ssl que não deixa o python baixar arquivos em https. Consegui rodar com python 2.7.2 e o site foi criado normalmente. Então, não pude confirmar se o problema é a versão do python.

@chinabhz você consegui verificar qual era a versão do python quando o problema ocorreu?

**Comment by idgserpro** [comment]
O que causa o erro é mesmo a versão 2.7.0 do python. Instalei o python 2.7.0 no CentOS 5 e o problema ocorreu. Como o problema aconteceu também com o @whereiswr no [Ubuntu 14.04](https://github.com/plonegovbr/portal.buildout/issues/21#issuecomment-180174386), concluo que é um problema com o python 2.7.0 e não como o sistema operacional.

**Comment by hvelarde** [comment]
@idgserpro acho que seria interessante colocar alguma nota de requerimentos mínimos de versão de Python.

ontem eu tive problemas com a versão 2.7.3 e o zc.buildout 2.5.
