### ISSUE TITLE
Repensar ferramentas de balanceamento de cargas

### ISSUE THREAD

**Issue by rodfersou** [plonegovbr/portal.buildout#25]
Ultimamente utilizamos Nginx, Varnish e Haproxy, segundo discussão do pull request #24 todas elas podem assumir o papel de balanceamento de carga.

Precisamos definir se existe a real necessidade do Haproxy a partir de testes e configurações dessas ferramentas para este propósito.

Uma atualização da documentação também será necessária a partir do resultado desses testes.

**Comment by ericof** [comment]
Meus 2 centavos:
O HA-Proxy faz uma coisa e a faz muito bem. Diferente do que acontece com Nginx e Varnish -- que também podem fazer, marginalmente, o balanceamento de carga, o HA-Proxy te dá relatórios e permite a rápida identificação de problemas.
Vale lembrar que o playbook do Plone para Ansible -- que é a ferramenta preferida pela comunidade Plone para automação de ambientes -- usa a stack Nginx -> Varnish -> HAProxy
ref: https://github.com/plone/ansible-playbook

**Comment by hvelarde** [comment]
contrário a crença popular, o HAProxy é um software complexo que não faz só uma coisa (mesmo que faça o balançamento de carga muito bem): ele fornece um conjunto de funcionalidades que podemos encontrar tanto no nginx quanto no Varnish (para uma lista completa de funcionalidades que se sobrepõem com o Varnish, por exemplo, podem ver [HAProxy and Varnish comparison](http://blog.haproxy.com/2012/07/04/haproxy-and-varnish-comparison/)).

o ponto é: vale a pena a sobrecarga administrativa de ter que aprender mais uma linguagem de configuração e ter que manter e monitorar mais um serviço quando um nível de performance praticamente igual pode ser obtido sem essa outra camada? eu não tenho a resposta e só que está cuidando da infra dum site pode decidir.

o nginx, por exemplo, é praticamente igual de rápido na tarefa de balançamento de carga do que o HAProxy; e não tem que acreditar na minha palavra, eu gosto sempre de argumentar meus pontos, já outras pessoas [fizeram testes que demostram isso](https://github.com/observing/balancerbattle).

eu já vi casos onde pessoas convencidas do uso do HAProxy como balanceador de carga, por querer ganhar 15ms da latência, deixaram sites mais lentos e instáveis que sem ele, e depois eram incapazes de encontrar facilmente onde era que estavam os problemas. os sistemas, entre mais complexos, mais difíceis são de manter e de predizer seu funcionamento.

se alguém quer usar o HAProxy pela interface de *poor man monitoring tool* que ele fornece, pode fazê-lo; mas não podemos obrigar ninguém a usar mais uma camada tecnológica que não é necessária para todos os casos.

nginx só, Varnish so, nginx com Varnish e nginx com Varnish e HAProxy são todas configurações válidas.

**Comment by davilima6** [comment]
+1: KISS. O Plone tem fama de complexo, portanto o que for possível simplificar nas instruções do IDG, melhor. Além disso, como o @hvelarde sugeriu,  um haproxy.cfg + documentação resolvem a questão para quem já tiver alcançado sucesso com menos partes móveis (production.cfg), mas ainda precisa dos relatórios mais específicos.

**Comment by ericof** [comment]
Infelizmente não posso compartilhar dados de performance e das vantagens da interface de monitoramento do HAProxy (sem dúvida, usar o NewRelic é infinitamente melhor) pois os contratos de consultoria tinham cláusulas de confidencialidade.
Como não estou mais ativo na comunidade, minha sugestão é que o @hvelarde, como mantenedor do Portal Padrão -- e experiente gestor de infra-estrutura de Plone -- implemente as modificações necessárias asap pois temos vários pedidos de ajuda na lista.

**Comment by hvelarde** [comment]
![ego-meme](https://cloud.githubusercontent.com/assets/341393/9506256/65e57f6c-4c1d-11e5-89d4-67584d4d91e0.png)

**Comment by domarques** [comment]
Talvez seja interessante separar haproxy, heartbeat, varnish, squid, nginx, apache etc. de um esquema minimo de configuração do plone/zeo e tais componentes adicionais ficassem como sugestões de implementação na documentação, onde o próprio usuário pudesse decidir qual utilizar conforme sua infraestrutura e/ou experiência. Neste cenário, é possível que usuários não muito experientes possam enfrentar mais dificuldades do que um esquema pré-definido pelo projeto.
