### ISSUE TITLE
Error ao executar o buildout

### ISSUE THREAD

**Issue by caduvieira** [plonegovbr/portal.buildout#29]
Ao executar o comando ./bin/buildout -c buildout.cfg

Rertorna erro informando que a extensão buildout-versions já está contida no novo buildout.

    While:
    Installing.
    Loading extensions.
    Error: Buildout now includes 'buildout-versions' (and part of the older 'buildout.dumppickedversions').
    Remove the extension from your configuration and look at the 'show-picked-versions' option in buildout's documentation.

**Comment by alexandroldl** [comment]
Estamos com o seguinte erro:

Error: There is a version conflict.
We already have: zope.interface 4.0.5


Cenário:
Description: Ubuntu 14.04.3 LTS
Release: 14.04
Codename: trusty

**Comment by alexandroldl** [comment]
needed = self.resolve(parse_requirements(requirements))
  File "/storage01/portal.buildout/eggs/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/storage01/portal.buildout/parts/instance1/etc/site.zcml", line 15.2-15.55
    ZopeXMLConfigurationError: File "/storage01/portal.buildout/parts/instance1/etc/package-includes/002-brasil.gov.portal-configure.zcml", line 1.0-1.61
    ZopeXMLConfigurationError: File "/storage01/portal.buildout/eggs/brasil.gov.portal-1.1.3-py2.7.egg/brasil/gov/portal/configure.zcml", line 11.2-11.38
    ZopeXMLConfigurationError: File "/storage01/portal.buildout/eggs/brasil.gov.portal-1.1.3-py2.7.egg/brasil/gov/portal/dependencies.zcml", line 5.2-5.41
    ZopeXMLConfigurationError: File "/storage01/portal.buildout/eggs/brasil.gov.agenda-1.0-py2.7.egg/brasil/gov/agenda/configure.zcml", line 11.4-11.39
    DistributionNotFound: zope.interface


Estamos enfrentando esses erro, já tentamos instalar no Ubuntu 12.10 / Ubuntu 14,
tentamos instalar o python-zope.interface e mesmo assim o erro ocorre!

**Comment by winstonf88** [comment]
@caduvieira @alexandroldl 

Edite o arquivo `buildout.d/base.cfg`e remova a linha `extensions = buildout-versions`.

**Comment by winstonf88** [comment]
@alexandroldl 

Suspeito que vc pode estar usando o Python errado, usando o Python do OS em vez da virtualenv.

**Comment by alexandroldl** [comment]
@winstonf88 

Obrigado pelo retorno.

Estou seguindo o roteiro definido em portal.buildout/docs.
Tomei o cuidado de rodar todos os comandos dentro da virtualenv e com usuário padrão.
Instalei todas as dependências exigidas na execução do ./bin/buildout -c buildout.cfg.


Porém, as instâncias não se iniciam devido ao seguinte erro.

```shell
1.0-py2.7.egg/brasil/gov/agenda/configure.zcml", line 11.4-11.39
    ZopeXMLConfigurationError: File "/storage01/portal.buildout/eggs/brasil.gov.tiles-1.0.7-py2.7.egg/brasil/gov/tiles/configure.zcml", line 9.4-9.39
    ZopeXMLConfigurationError: File "/storage01/portal.buildout/eggs/collective.cover-1.0a11-py2.7.egg/collective/cover/configure.zcml", line 15.2-15.37
    ZopeXMLConfigurationError: File "/storage01/portal.buildout/eggs/plone.app.stagingbehavior-0.1b4-py2.7.egg/plone/app/stagingbehavior/configure.zcml", line 8.4-8.39
    ZopeXMLConfigurationError: File "/storage01/portal.buildout/eggs/Products.CMFPlone-4.3.3-py2.7.egg/Products/CMFPlone/configure.zcml", line 98.4-102.10
    ZopeXMLConfigurationError: File "/storage01/portal.buildout/eggs/sc.embedder-1.0b4-py2.7.egg/sc/embedder/configure.zcml", line 11.4-11.39
    ZopeXMLConfigurationError: File "/storage01/portal.buildout/eggs/zope.intid-3.7.2-py2.7.egg/zope/intid/configure.zcml", line 7.4
    ConfigurationError: ('Invalid directive', u'factory')

```

**Comment by domarques** [comment]
@alexandroldl acompanhastes o https://identidade-digital-de-governo-plone.readthedocs.org/en/latest/base/ ou direto nos arquivos do diretório docs do repositório?

@hvelarde percebi agora que aquelas modificações que havia feito no #23 não estão no RtfD (sphinx), é algo que eu deveria ter feito naquela ocasião ou é necessário a intervenção de alguém para isso?

**Comment by alexandroldl** [comment]
Sim, segui o roteiro de ambos. Eu já havia conseguido instalar antes mas
tivemos problemas com o servidor e tive que reinstalar tudo. Algo com a
versão do Ubuntu pode estar influenciando?

Obrigado.
Em 22/10/2015 10:16 PM, "André Domarques" <notifications@github.com>
escreveu:

**Comment by hvelarde** [comment]
@domarques não faço ideia; tal vez o @ericof saiba.

**Comment by idgserpro** [comment]
@caduvieira o commit https://github.com/plonegovbr/portal.buildout/commit/b28a53e2f60670e0a4e28cbf9dcebdcd4f313df7 corrige o relato original dessa issue, não é?

**Comment by caduvieira** [comment]
Sim

**Comment by idgserpro** [comment]
@alexandroldl vou fechar essa issue e se você ainda estiver tendo problema, favor abrir outro relato com o seu problema especifico.
