### ISSUE TITLE
Criar releases para o portal padrão

### ISSUE THREAD

**Issue by caduvieira** [plonegovbr/portal.buildout#31]
Criar tags/releases aqui no portal.padrao para saber qual a versão estável no portal buildout

**Comment by domarques** [comment]
As tags devem corresponder aos releases do portal.padrao para facilitar de alguma forma?

**Comment by idgserpro** [comment]
Recomendo sim seguir os releases do portal.padrao como disponibilizados em https://github.com/plonegovbr/portalpadrao.release. Seria interessante ter essa informação inclusive na documentação do portal.buildout.

A questão é que agora antes do lançamento de cada novo release, o portal.buildout também terá de ser revisado para não estar "quebrado" para aquele release em questão.

**Comment by caduvieira** [comment]
Também recomendo corresponder. Assim teremos versões mais estáveis do portal.buildout. Alguns dos problemas que as pessoas estão lidando é que ao clonar o portal.buildout, naquele momento, está quebrado alguma coisa e fica-se correndo para corrigir.

**Comment by hvelarde** [comment]
acabei de criar o tag 1.1.3 https://github.com/plonegovbr/portal.buildout/releases
