### ISSUE TITLE
Error: The referenced section, 'users', was not defined.

### ISSUE THREAD

**Issue by winstonf88** [plonegovbr/portal.buildout#32]
Está acontecendo este erro ao instalar um portal novo.

```bash
Installing 'mr.developer'.
We have the distribution that satisfies 'mr.developer==1.21'.
mr.developer: Queued 'brasil.gov.portlets' for checkout.
mr.developer: Updated 'brasil.gov.portlets' with git.
Installing 'zc.buildout', 'setuptools'.
We have the distribution that satisfies 'zc.buildout==1.7.1'.
We have the distribution that satisfies 'setuptools==0.6c11'.
Develop: '/path/to/portal.buildout/src/brasil.gov.portlets'
Installing 'zc.recipe.egg'.
We have the distribution that satisfies 'zc.recipe.egg==1.3.2'.
While:
  Installing.
  Getting section instance.
  Initializing section instance.
  Getting option instance:effective-user.
  Getting section users.
Error: The referenced section, 'users', was not defined.
```

**Comment by hvelarde** [comment]
@domarques isso é consequência do #23; pode nos ajudar, por favor?

**Comment by domarques** [comment]
@hvelarde, @winstonf88 estarei verificando assim que possível.

**Comment by domarques** [comment]
Pelo que pude verificar rapidamente deve está relacionado a remoção do buildout.d/settings.cfg, pois suponho que @winstonf88 deva ter utilizado o development.cfg. Desta forma, ou retornamos com o arquivo settings.cfg para este caso ou que tais diretivas sejam adicionadas ao development.cfg .

**Comment by idgserpro** [comment]
@domarques minha sugestão é que o [effective-user](https://github.com/plonegovbr/portal.buildout/blob/337ae32cad4324ea9a0805abc04ae7e60f453319/buildout.d/base.cfg#L14) seja removido do base.cfg e adicionado no [production.cfg](https://github.com/plonegovbr/portal.buildout/blob/337ae32cad4324ea9a0805abc04ae7e60f453319/production.cfg). Não faz sentido ter effective-user no desenvolvimento.

**Comment by winstonf88** [comment]
O que acham de fazer releases do `portal.buildout` para que esse problema não ocorra?
Se no futuro, por acaso, tivermos outro problema desses. A pessoa pode baixar uma versão de instalação "antiga" e não vai impedir que instalem o portal.

**Comment by idgserpro** [comment]
@winstonf88 boa ideia já pedida aqui: https://github.com/plonegovbr/portal.buildout/issues/31

**Comment by hvelarde** [comment]
podemos usar tags, mas isso implica também que a pessoa que vai instalar vai precisar entender esses conceitos adicionais; sinceramente precisamos distribuir o portal de outros jeitos como já foi feito no passado: VM, containers...

**Comment by winstonf88** [comment]
@hvelarde Eu acho que não. Podemos criar as tags/release aqui pelo github mesmo e colocar um link para download no `README.rst` ou na documentação.

**Comment by domarques** [comment]
Concordo com a sugestão de criar as tags acompanhada da documentação.

Em relação à distribuição, já me disponibilizei a auxiliar nesse sentido, seja no docker, puppet, ansible etc. Quem mais puder ajudar, será muito bem-vindo! Não se acanhem ;)

Quanto ao problema corrente, para que a instalação não fique comprometida, estarei preparando o pull request e envio assim que possível.

**Comment by hvelarde** [comment]
@domarques podemos começar com Vagrant? da para colocar todo o ambiente num container Docker só? obvio que seria só para avaliar o IDGB.

@winstonf88 @idgserpro vamos abrirmos issues para isso, né?

**Comment by winstonf88** [comment]
+1

**Comment by idgserpro** [comment]
Sim. Isso deve ser discutido em outra issue.

**Comment by hvelarde** [comment]
@domarques pronto: https://github.com/plonegovbr/brasil.gov.portal/issues/245 e https://github.com/plonegovbr/brasil.gov.portal/issues/245

**Comment by domarques** [comment]
Caros: Ainda não conclui o pull request pois ainda não encontrei uma solução para o problema relacionado ao collective.transmogrify, dá pra resolver temporariamente na instância de desenvolvimento usando o mr.developer (fazendo o checkout do repo). Fiz um teste rápido e desconfio ser algo relacionado ao setuptools (2.2). Usei o collective.minimalplone4 com o collective.transmogrify e setuptools (18.4) e não apresentou o mesmo problema.

**Comment by hvelarde** [comment]
@domarques qual é o problema?

**Comment by domarques** [comment]
@hvelarde: é relacionado ao setuptools, descrevi em https://github.com/plonegovbr/portal.buildout/issues/33#issuecomment-155056516

**Comment by idgserpro** [comment]
@hvelarde você removeu o ```effective-user``` do [base.cfg](https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/base.cfg) mas não adicionou o ```effective-user``` no [production.cfg](https://github.com/plonegovbr/portal.buildout/blob/master/production.cfg). O effective-user faz sentido em ambientes de produção.

**Comment by idgserpro** [comment]
@hvelarde opa, vi que o effective-user já existia no production.cfg.
