### ISSUE TITLE
Release 1.1.3 do portal.buildout não instala corretamente

### ISSUE THREAD

**Issue by caduvieira** [plonegovbr/portal.buildout#34]
Pelo procedimento definido em https://identidade-digital-de-governo-plone.readthedocs.org/en/latest/producao/ e fazendo checkout de tag 1.1.3 
ocorre o seguinte erro:

While:
  Installing.
  Loading extensions.
Error: Buildout now includes 'buildout-versions' (and part of the older 'buildout.dumppickedversions').
Remove the extension from your configuration and look at the 'show-picked-versions' option in buildout's documentation.

Creio que esse erro já tenha sido corrigido em commits após a criação da tag.

Sugiro retirar a tag e criar em um commit estável.

Podiamos modificar a documentação para que o checkout da tag esteja presente e problemas de versões dos pacotes não sejam recorrentes na lista de discussão.

**Comment by hvelarde** [comment]
@caduvieira eu sugiro colocar uma nota na documentação como um bug conhecido

**Comment by caduvieira** [comment]
Ok. Concordo

**Comment by winstonf88** [comment]
outro problema que está impedindo a instalação
```
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Updating _mr.developer.
Installing instance.
Getting distribution for 'collective.transmogrifier==1.5'.
error: [Errno 2] No such file or directory: '/tmp/easy_install-XzwoTw/collective.transmogrifier-1.5/README.rst'
An error occurred when trying to install collective.transmogrifier 1.5. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'collective.transmogrifier==1.5'.
Error: Couldn't install: collective.transmogrifier 1.5
```

Só mudar o versions para a versão 1.5.1

**Comment by idgserpro** [comment]
@hvelarde você pode adicinar a versão 1.5.1 no novo release 1.1.3.1?

**Comment by hvelarde** [comment]
@idgserpro https://github.com/plonegovbr/portalpadrao.release/commit/1db9d9369d2783e7ab9d8a517582afeb24270e83

**Comment by idgserpro** [comment]
@hvelarde falta atualizar http://downloads.plone.org.br/release/1.1.3.1/versions.cfg ?

E sim. Pode criar a tag. :+1:

**Comment by hvelarde** [comment]
ele se atualiza sozinho acada 5 minutos e já está atualizado.

**Comment by hvelarde** [comment]
tag criada https://github.com/plonegovbr/portal.buildout/tree/1.1.3.1

**Comment by idgserpro** [comment]
@caduvieira você poderia documentar o problema da tag 1.1.3? Você poderia também documentar o uso de tags no [producao.rst](https://github.com/plonegovbr/portal.buildout/blob/master/docs/producao.rst)?

**Comment by idgserpro** [comment]
@caduvieira você pode documentar o problema da tag 1.1.3, como sujerido pelo @hvelarde?
