### ISSUE TITLE
Criar integração contínua para o repositório

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/portal.buildout#35]
Devido aos problemas que estamos tendo com o buildout, sugiro criar integração contínua no travis para o portal.buildout. Poderia ser testado se os buildouts de produção e desenvolvimento são executados corretamente.

**Comment by hvelarde** [comment]
não é uma tarefa simples por o Travis teria que ser acionado em cascada quando uma dependência é atualizada.

@jeanferri como estão resolvendo isso vocês no Portal Modelo?

**Comment by idgserpro** [comment]
@hvelarde eu não estava pensando em acionar o Travis quando um dependência fosse alterada. Acionar o Travis quando o portal.buildout fosse alterado já estaria bom.

**Comment by hvelarde** [comment]
@idgserpro favor revisar o PR, atualizar a documentação de desenvolvimento e mesclar
