### ISSUE TITLE
Erro na instalação do portal padrão

### ISSUE THREAD

**Issue by ricardommoreira** [plonegovbr/portal.buildout#37]
Olá, não consigo instalar o portal padrão.

Sigo os passos da instalação e ao executar o comando:
./bin/buildout -c buildout.cfg

Ocorre o seguinte erro:

Installing zeo.
Created directory /opt/portal.buildout/parts/zeo
Created directory /opt/portal.buildout/parts/zeo/etc
Created directory /opt/portal.buildout/parts/zeo/var
Created directory /opt/portal.buildout/parts/zeo/log
Created directory /opt/portal.buildout/parts/zeo/bin
Wrote file /opt/portal.buildout/parts/zeo/etc/zeo.conf
Wrote file /opt/portal.buildout/parts/zeo/bin/zeoctl
Changed mode for /opt/portal.buildout/parts/zeo/bin/zeoctl to 755
Wrote file /opt/portal.buildout/parts/zeo/bin/runzeo
Changed mode for /opt/portal.buildout/parts/zeo/bin/runzeo to 755
Generated script '/opt/portal.buildout/bin/zeo'.
Generated script '/opt/portal.buildout/bin/zeopack'.
Generated script '/opt/portal.buildout/bin/repozo'.
Installing instance.
Getting distribution for 'brasil.gov.portal==1.1.3'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Got brasil.gov.portal 1.1.3.
Getting distribution for 'plone4.csrffixes'.
warning: no previously-included files matching '*pyc' found anywhere in distribution
Got plone4.csrffixes 1.0.9.
Getting distribution for 'cssselect'.
no previously-included directories found matching 'docs/_build'
zip_safe flag not set; analyzing archive contents...
Got cssselect 0.9.1.
Getting distribution for 'collective.monkeypatcher==1.0.1'.
Got collective.monkeypatcher 1.0.1.
The constraint, 2.0.4, is not consistent with the requirement, 'plone.locking>=2.0.8'.
While:
  Installing instance.
Error: Bad constraint 2.0.4 plone.locking>=2.0.8

**Comment by hvelarde** [comment]
você está tentando instalar com qual configuração? produção ou desenvolvimento?

duplica #33, por favor acompanhe a solução ai.

**Comment by hvelarde** [comment]
@ricardommoreira por favor atualize seu repo (`git pull`) e rode novamente o buildout; isso aqui deveria corregir: https://github.com/plonegovbr/portal.buildout/commit/60d495354b939c7454e32365fa48e6a0fca6b4fd

**Comment by ricardommoreira** [comment]
Olá Héctor, estou tentando instalar o produção.
Em 30/11/2015 11:46, "Héctor Velarde" <notifications@github.com> escreveu:

**Comment by idgserpro** [comment]
@ricardommoreira o problema foi resolvido?
