### ISSUE TITLE
Criar tag que contemple o Plone Hotfix 20151208

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/portal.buildout#38]
Uma vez que estamos recomendando [utilização de tags](https://github.com/plonegovbr/portal.buildout/commit/9c03ffb671b6e818e345f6e42eb8142414041875), recomendo a criação de uma tag que contemple o [Plone Hotfix 20151208](https://github.com/plonegovbr/portal.buildout/commit/c2aa64598c0a5d692eb9c00095d1013e197ebcd1).

**Comment by hvelarde** [comment]
precisamos criar um novo release do brasil.gov.portal?

**Comment by idgserpro** [comment]
Sim uma vez que:

- As boas práticas da documentação indicam que uma tag deve ser usada e não diretamente o *master* (que é onde está a dependência do hotfix);
- É um hotfix de segurança, portanto, muito importante de se aplicar a todos novos portais IDG.

**Comment by hvelarde** [comment]
no próximo release do Plone 4.3 isso vai ser inclusso por padrão: https://github.com/plone/Products.CMFPlone/pull/1305/files

**Comment by idgserpro** [comment]
Nada de tag ainda?

**Comment by hvelarde** [comment]
@idgserpro tem que combinar com o @winstonf88 para isso; eu não estou envolvido direitamente agora, só estou acompanhando.

**Comment by idgserpro** [comment]
@winstonf88 você pode criar a tag?

**Comment by idgserpro** [comment]
@winstonf88 você pode criar a tag para contemplar o Plone Hotfix 20151208?

**Comment by idgserpro** [comment]
@winstonf88 @hvelarde @caduvieira  se não tiver alguém para gerar tag do portal.buildout constantemente, sou a favor de remover da documentação o [uso do checkout](https://github.com/plonegovbr/portal.buildout/commit/9c03ffb671b6e818e345f6e42eb8142414041875). Alguns motivos:

- Precisa que a tag seja gerada constantemente (vai sobrecarregar os desenvolvedores)
- Vamos ter mais um hotfix de segurança que irá ficar sem ser aplicado se o usuário fizer o checkout (que é o motivo desse relato)
- A atual tag não está funcionando.
- Parece que o pessoal [não está usando](https://github.com/plonegovbr/portal.buildout/issues/48#issuecomment-208954263)

Opiniões?

**Comment by caduvieira** [comment]
Entendo. Mas eh uma troca pois pode ter algo que quebre. E a idéia do tag seria nos builds estáveis. Mas se está gerando problema é ninguém usa sou a favor de tirar também

**Comment by hvelarde** [comment]
eu acho que é cedo para decidir sobre isso; precisamos ter informação sobre se essa funcionalidade está sendo usado ou não.

**Comment by idgserpro** [comment]
@hvelarde fora se o pessoal está utilizando ou não, o problema mais grave é que a tag fica desatualizada porque não estamos gerando tags. A tag 1.1.3.1 por exemplo, não está funcionando.

**Comment by hvelarde** [comment]
@idgserpro mas não estamos gerando simplesmente porque não temos uma nova versão; sugiro esperar para fazer uma avaliação depois.

**Comment by idgserpro** [comment]
@hvelarde mas temos que gerar uma tag pois a tag atual está com erro. E semana que vem teremos um hotfix, e precisará ser gerado uma tag que contenha esse hotfix.

**Comment by hvelarde** [comment]
@idgserpro concordo; @seidgy por favor tome nota que não temos recursos para fazer esse release.

**Comment by seidgy** [comment]
Boa tarde @hvelarde, @idgserpro. Comecei a atuar recentemente com qualquer tipo de iteração com o portal padrão. Portanto sou leigo em relação ao assunto. Para gerar esse release precisaria de orientação ou passo a passo dos procedimentos que devem ser realizados.

**Comment by idgserpro** [comment]
@seidgy aqui estamos falando somente da criação de uma tag para o portal.buildout.

@hvelarde @winstonf88 alias, o que estamos esperando para lançar o release 1.1.4 do IDG? Proponho esperar o novo hotfix e lançar o release. Sendo os passos:

- Adicionar o hotfix
- Lançar um release do brasil.gov.portlet
- Lançar um release do brasil.gov.title
- Atualizar o collective.cover para 1.1b1
- Criar a tag no portal.buildout

Já que estamos sem braços para corrigir novos erros, vamos lançar esse release, que já corrigi muita coisa, e mais pra frente corrigimos mais erros. Esse novo release é muito importante porque atualiza também o Plone.

**Comment by idgserpro** [comment]
Adicionei o hotfix Products.PloneHotfix20151208:

https://github.com/plonegovbr/portal.buildout/commit/d8b0623cf4e2baa1e90ef2de81e8e63f043c5846

@winstonf88 você pode gera releases do brasil.gov.portlet e do brasil.gov.tiles?

**Comment by idgserpro** [comment]
Gerada nova tag [1.1.4](https://github.com/plonegovbr/portal.buildout/releases/tag/1.1.4)
