### ISSUE TITLE
Explicitar pra não usar sudo na instalação?

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/portal.buildout#40]
Após uma [troca de mensagens na lista](https://listas.interlegis.gov.br/pipermail/plonegov-br/2016-January/003498.html), mesmo na documentação não informando o uso de sudo, seria o caso de colocar um warning **não use sudo** e já [colocar até uma explicação do motivo disso atrapalhar a instalação](http://askubuntu.com/a/478001)?

É muito comum o uso de `sudo` para instalação de pacotes, muitas vezes um usuário executa mentalmente o passo até mesmo de forma mecânica.

**Comment by hvelarde** [comment]
+1

**Comment by idgserpro** [comment]
Resolvido por https://github.com/plonegovbr/portal.buildout/pull/42
