### ISSUE TITLE
Erro na instalação no momento compilaçãoi buildout.cfg

### ISSUE THREAD

**Issue by cesarqr** [plonegovbr/portal.buildout#47]
Amigos bom dia quase boa tarde.
Tenho uma dificuldade na configuração do ambiente de produção que se apresenta quando da compilação do buildout.cfg. Abaixo apresento o que o sistema retorna para mim:

(py27)plone@hogo-sha ~/portal.buildout $ ./bin/buildout -c buildout.cfg
Updating zeo.
Installing instance.
Getting distribution for 'lxml==2.3.6'.
While:
  Installing instance.
  Getting distribution for 'lxml==2.3.6'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/opt/plone/portal.buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1866, in main
    getattr(buildout, command)(args)
  File "/opt/plone/portal.buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 625, in install
    installed_files = self[part]._call(recipe.install)
  File "/opt/plone/portal.buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py", line 1345, in _call
    return f()
  File "/opt/plone/portal.buildout/eggs/plone.recipe.zope2instance-4.2.18-py2.7.egg/plone/recipe/zope2instance/__init__.py", line 113, in install
    installed.extend(self.install_scripts())
  File "/opt/plone/portal.buildout/eggs/plone.recipe.zope2instance-4.2.18-py2.7.egg/plone/recipe/zope2instance/**init**.py", line 617, in install_scripts
    requirements, ws = self.egg.working_set(['plone.recipe.zope2instance'])
  File "/opt/plone/portal.buildout/eggs/zc.recipe.egg-1.3.2-py2.7.egg/zc/recipe/egg/egg.py", line 101, in working_set
    **kw)
  File "/opt/plone/portal.buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/easy_install.py", line 1079, in install
    return installer.install(specs, working_set)
  File "/opt/plone/portal.buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/easy_install.py", line 931, in install
    ws, self._always_unzip):
  File "/opt/plone/portal.buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/easy_install.py", line 739, in _get_dist
    dist = self._fetch(avail, tmp, self._download_cache)
  File "/opt/plone/portal.buildout/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/easy_install.py", line 702, in _fetch
    new_location = self._index.download(dist.location, tmp)
  File "/opt/plone/portal.buildout/eggs/setuptools-0.6c11-py2.7.egg/setuptools/package_index.py", line 392, in download
    found = self._download_url(scheme.group(1), spec, tmpdir)
  File "/opt/plone/portal.buildout/eggs/setuptools-0.6c11-py2.7.egg/setuptools/package_index.py", line 614, in _download_url
    return self._attempt_download(url, filename)
  File "/opt/plone/portal.buildout/eggs/setuptools-0.6c11-py2.7.egg/setuptools/package_index.py", line 621, in _attempt_download
    headers = self._download_to(url, filename)
  File "/opt/plone/portal.buildout/eggs/setuptools-0.6c11-py2.7.egg/setuptools/package_index.py", line 557, in _download_to
    block = fp.read(bs)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
error: [Errno 104] Connection reset by peer

(py27)plone@hogo-sha ~/portal.buildout $ 

Posso ter sido desatento na busca, mas não encontrei erros semelhantes em fórum, tampouco no google.
Alguém pode me ajudar?

**Comment by idgserpro** [comment]
@cesarqr parece que foi um problema na hora baixar algum pacote:

http://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean/1434506

Tente rodar o buildout mais tarde.

**Comment by cesarqr** [comment]
@idgserpro então, esse erro já é antigo, eu tentei fazer esta instalação no final do ano passado e tive o mesmo problema, ontem também... teria algo mais que levasse a este erro de conexão?

**Comment by idgserpro** [comment]
@cesarqr removi o meu cache de eggs e rodei o buildout. O buildout consegui baixar todos os pacotes. Ou seja, o problema é com você (com sua rede). Você está atrás de algum proxy?

**Comment by cesarqr** [comment]
Não estou atrás de proxy, tem algo mais de especial para conectar que possa ser bloqueado? Nossa rede esta atrás de um PaloAlto...

**Comment by idgserpro** [comment]
@cesarqr o erro sempre ocorre quando o buildout tenta baixar o lxml ou varia?

**Comment by cesarqr** [comment]
Sempre aí, ele trava nesta etapa.

**Comment by idgserpro** [comment]
@cesarqr veja se você consegue baixar o ```lxml``` com o wget:

```bash
cd /tmp
wget https://pypi.python.org/packages/source/l/lxml/lxml-2.3.6.tar.gz#md5=d5d886088e78b1bdbfd66d328fc2d0bc
```

**Comment by cesarqr** [comment]
Consegui!

**Comment by cesarqr** [comment]
plone@hogo-sha /tmp $ wget https://pypi.python.org/packages/source/l/lxml/lxml-2.3.6.tar.gz#md5=d5d886088e78b1bdbfd66d328fc2d0bc
--2016-03-31 16:48:23--  https://pypi.python.org/packages/source/l/lxml/lxml-2.3.6.tar.gz
Resolvendo pypi.python.org (pypi.python.org)... 104.156.82.223
Conectando-se a pypi.python.org (pypi.python.org)|104.156.82.223|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 3169779 (3,0M) [application/octet-stream]
Salvando em: “lxml-2.3.6.tar.gz.1”

100%[======================================================================================================================================================>] 3.169.779   1,58MB/s   em 1,9s

2016-03-31 16:48:25 (1,58 MB/s) - “lxml-2.3.6.tar.gz.1” salvo [3169779/3169779]

**Comment by idgserpro** [comment]
@cesarqr tente agora:

```bash
cd /tmp
wget http://dist.plone.org/release/4.3.7/lxml-2.3.6.tar.gz
```

**Comment by cesarqr** [comment]
Também foi bem sucedido o download

**Comment by idgserpro** [comment]
@cesarqr qual é o sistema operacional e versão que você está utilizando? Qual é a versão do python?

**Comment by cesarqr** [comment]
Linux version 3.16.0-38-generic (buildd@allspice) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #52~14.04.1-Ubuntu SMP 

Distro: "Linux Mint 17.2 Rafaela"

Versão do kernel atual: 3.16.0-38-generic

Versão Py: Python 2.7.6

**Comment by idgserpro** [comment]
@cesarqr segui as instruções em:

https://github.com/plonegovbr/portal.buildout/blob/master/docs/base.rst

e

https://github.com/plonegovbr/portal.buildout/blob/master/docs/producao.rst

em um Ubuntu 14.04 e com o python 2.7.6 e tudo correu bem. Você segui as instruções acima? Recomendo você remover a pasta ```portal.buildout``` e seguir exatamente as instruções acima.

**Comment by idgserpro** [comment]
A única coisa que eu não fiz foi o [git checkout tags/X.X.X.X](https://github.com/plonegovbr/portal.buildout/blob/master/docs/producao.rst#usando-repositório), de forma a utilizar o master do portal.buildout.

**Comment by cesarqr** [comment]
Ainda falhou, mas daí instalei os pacotes que deram esse erro de peer com o easy_install e mandei compilar de novo, parecia que ia terminar a instalação e tive um contratempo...

```
(py27)plone@hogo-sha ~/portal.buildout $ ./bin/buildout -c buildout.cfg
While:
  Installing.
  Getting section instance.
  Initializing section instance.
  Getting option instance:zeo-address.
  Getting section zeo.
  Initializing section zeo.
  Installing recipe plone.recipe.zeoserver.
Error: There is a version conflict.
We already have: ZopeUndo 4.1

```

**Comment by idgserpro** [comment]
@cesarqr então ou você está com algum problema de rede ou você está com algum pacote do sistema operacional faltando ou a mais. Você instalou os pacotes como indicado [aqui](https://github.com/plonegovbr/portal.buildout/blob/master/docs/base.rst)?

Quando você diz que instalou com o ```easy_install```, você quis disser com o easy_install da virtualenv, certo? Você está utilizando virtualenv?

Como você podê ver, não é uma boa utilizar o easy_install da virtualenv que você utiliza para executar o buildout. Ele vai baixar versões que não são compatíveis como o seu projeto. Recomendo você excluir a pasta ```/opt/plone/portal.buildout/py27``` e cria uma nova virtualenv. A virtualenv sempre deve ficar 'limpa'.

**Comment by idgserpro** [comment]
@cesarqr você conseguiu executar o buildout?

**Comment by cesarqr** [comment]
Executei, mas caiu no mesmo erro meu caro...

2016-04-13 11:53 GMT-03:00 idgserpro <notifications@github.com>:

> @cesarqr <https://github.com/cesarqr> você conseguiu executar o buildout?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/plonegovbr/portal.buildout/issues/47#issuecomment-209488279>
>



-- 
Júlio César Medina Madruga
Técnico de Tecnologia de Informação
Núcleo de Tecnologia da Informação
Universidade Federal do Rio Grande - FURG

**Comment by idgserpro** [comment]
@cesarqr você pode tentar utilizar a ultima versão do setuptools e do zc.buildout. Edite o seu ```buildout.cfg``` acrescentando ao final do arquivo:

```
[versions]
setuptools =
zc.buildout =
```

Depois execute:

```bash
source py27/bin/activate
python bootstrap.py -c buildout.cfg
./bin/buildout -c buildout.cfg
```

**Comment by idgserpro** [comment]
@cesarqr você consegui executar o buildout com as últimas versões do setuptools e do zc.buildout?

**Comment by idgserpro** [comment]
@cesarqr conseguiu testar com as últimas versões como mencionado acima? Iremos fechar esse relato.

**Comment by idgserpro** [comment]
@cesarqr conseguiu testar com as últimas versões como mencionado acima? Sençao iremos fechar esse relato por falta de retorno.
