### ISSUE TITLE
Erro durante a instalção do portal padrão...

### ISSUE THREAD

**Issue by fernandorochati** [plonegovbr/portal.buildout#48]
Durante a instalação do portal padrão ocorreram vários problemas de sintax. E depois da instalação não consegui iniciar os serviços, os scripts de inicialização não estavam dentro do .bin.

**Comment by idgserpro** [comment]
@fernandorochati qual manual de instalação você segui? Qual é o seu sistema operacional e versão? Qual a versão do python? É necessário você enviar o log da execução do buildout.

**Comment by fernandorochati** [comment]
Já deu certo aqui... Executei todos os passos, de menos  este "cd $HOME/portal.buildout
# X.X.X.X é a última tag em releases, presente em
# https://github.com/plonegovbr/portal.buildout/releases
git checkout tags/X.X.X.X". Obrigado pela ajuda.
