### ISSUE TITLE
Explicitar na documentação as necessidades de bibliotecas para executar o buildout

### ISSUE THREAD

**Issue by caduvieira** [plonegovbr/portal.buildout#51]
Atualmente precisa do Python.h para o Zodb, libxslt-dev para o lxml, libyaml-dev para yaml, e o decoder para jpeg durante a execução do portal. Talvez precise de mais algum.

Nenhuma dessas dependências são instaladas por default no Ubuntu 16.04 LTS.

**Comment by hvelarde** [comment]
@caduvieira eu instelei ontem um portal no Ubuntu 16.04 utilizando o mesmo procedimento descrito para Ubuntu 12.04.

é importante saber que o Python 2.7 incluso atualmente no Ubuntu 16.04 está bugado e não vai funcionar:

https://community.plone.org/t/ubuntu-16-04-zope-instance-terminated-by-sigsegv-core-dumped/2059?u=hvelarde

um workaround está descrito aqui:

https://bugs.launchpad.net/ubuntu/+source/python2.7/+bug/1580577/comments/11

mas deve ter cuidado de voltar para atrás apos da criação do virtualenv ou seu pacotes podem ficar quebrados e as atualizações de segurança inabilitadas.

**Comment by caduvieira** [comment]
Obrigado @hvelarde . Com o workaround funcionou com o mesmo procedimento do 12.04. :+1:
