### ISSUE TITLE
Incorporar z3c.checkversions/plone.versioncheck?

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/portal.buildout#60]
Pode ser útil para novos releases, verificar as atualizações disponíveis dos pacotes pinados.

É necessário passar um versions.cfg para essa verificação, achamos que o conceito de versions-sem-extends.sh em https://github.com/plonegovbr/portalpadrao.release/blob/9584fcdf5dee7793936328919bc0fbb71530ff2d/versions-sem-extends.sh pode ser útil para esse processo.

Ou então usar o pacote mais novo, plone.versioncheck.

**Comment by hvelarde** [comment]
o [checkversions] está ai desde o primeiro dia:

https://github.com/plonegovbr/portal.buildout/blob/1.4/development.cfg#L36-L38

**Comment by idgserpro** [comment]
Acho que a idéia aqui mais era de colocar no processo de release a verificação de versões novas com o uso dessa extensão.

**Comment by hvelarde** [comment]
beleza, vou atualizar o documento então; preciso revisão das coisas pendentes, por favor.
