### ISSUE TITLE
Revisar arquivos de documentação para evitar limite de 80 caracteres

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/portal.buildout#73]
https://docs.plone.org/develop/styleguide/python.html#line-length

> The line length rule also applies to non-python source files, such as .zcml files, but is a bit more relaxed there. It explicitly does not aply to documentation .rst files. For .rst files including the package documentation but also README.rst, CHANGES.rst and doctests, use semantic linebreaks and add a line break after each sentence. See the :doc:`REST styleguide </about/rst-styleguide.html#line-length-translations>`_ for the reasoning behind it.

**Comment by idgserpro** [comment]
Motivado por https://github.com/plonegovbr/portal.buildout/pull/72

Outros arquivos podem estar com o mesmo problema.

**Comment by hvelarde** [comment]
@idgserpro faz sentido manter esta issue aberta ou podemos ir consertando aos poucos?

**Comment by idgserpro** [comment]
@hvelarde acabou que concordei com você. Dificilmente alguém vai refazer tudo. E se ao invés disso adicionássemos uma ISSUE_TEMPLATE avisando disso nos PRs de documentação do repositório?
