### ISSUE TITLE
Algumas versões para atualizar

### ISSUE THREAD

**Issue by claytonc** [plonegovbr/portal.buildout#91]
Algumas versões que poderiam aproveitar para atualizar:

- [x] plone.app.themingplugins = 1.0
- [x] Products.PloneFormGen = 1.7.23
- [ ] plone.api = 1.8.1
- [x] collective.portlet.calendar = 1.0b3
- [x] plone.app.contenttypes = 1.1.2 ou 1.1.5
- [x] raptus.autocompletewidget = 1.0b4

**Comment by hvelarde** [comment]
não vamos conseguir atualizar o plone.api ainda: https://github.com/plone/plone.api/issues/364
